version: '2'

services:
  myDatabase:
    image: psql:own
    expose:
      - 5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  data: {}