apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    type: prod
spec:
  template:
     metadata:
       name: myapp
       labels:
         type: prod
     spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 3

