apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    type: prod
spec:
  template:
     metadata:
       name: myapp
       labels:
         type: prod
     spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 2
  selector:
     matchLabels:
        type: prod
  

