apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deploy
    labels:
        name: postgres-app-deploy
        app: demo
spec:
    replicas: 1
    selector:
        matchLabels:
            name: postgres-pod
            app: demo
    template:
        metadata:
            name: postgres-pod
            labels:
                name: postgres-pod
                app: demo
        spec:
            containers:
                - name: postgres
                  image: postgres
                  ports:
                    - containerPort: 5432
                  env:
                    - name: POSTGRES_USER
                      value: "postgres"
                    - name: POSTGRES_HOST_AUTH_METHOD
                      value: trust