apiVersion: v1
kind: Service
metadata:
    name: voting
    labels:
        name: voting-service
        app: demo
spec:
    type: NodePort
    ports:
        - targetPort: 80
          port: 80
          nodePort: 30004
    selector:
        name: voting-app-pod
        app: demo